GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/1432423

###
DELETE http://localhost:3001/api/persons/651b7ad362e32a30373c1a9e

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sonia Raqui",
    "number": "5541"
}